[browser]
gatherUsageStats = false

[server]
runOnSave = false

# [theme]
# Primary accent for interactive elements
# primaryColor = '#7792E3'

[theme]
# base="light"
backgroundColor="#9db2bf"
# font="monospace"

# Background color for the main content area
# backgroundColor = '#9DB2BF'

# Background color for sidebar and most interactive widgets
# secondaryBackgroundColor = '#B9F1C0'

# Color used for almost all text
# textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
# font = "sans serif"
